### ISSUE TITLE
BUG: In search results, the markup from pages (specifically KTPP page) causes a design error.

### ISSUE THREAD

**Issue by wrightcj03** [a8cteam51/onbeing#48] opened 2017-03-14 19:52 UTC
Page that is broken: https://www.onbeing.org/ktpp/

Shows up in search results like this: http://onbeing.org/?s=krista+tippett&op=Search&form_build_id=&form_id=search_block_form58c042866f61e8538c9a26a6False

![screenshot_2017-03-08_11 46 04](https://cloud.githubusercontent.com/assets/16471307/24016465/344e0698-0a5a-11e7-8f43-f6f8b4fa6271.png)

**Comment by sarahmonster** [comment] 2017-06-06 12:17
Duplicate of #38.

**Closed by sarahmonster** 2017-06-06 12:17 UTC
Labels: bug, design, low-priority, Migrated from Trello
